# Site settings
title: Iwona Sobieraj
email: i.sobieraj[at]surrey.uk
description: > # this means to ignore newlines until "baseurl:"
  Exploring Machine Listening
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  iwonasob

# Build settings
markdown: kramdown

# Other options
permalink: news/:year/:month/:title
job.title: "PhD Student"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
